networks:
  trs-app:

services:
  db:
    image: sunrajmohawk/trsdb
    networks:
      - trs-app
    environment:
      MYSQL_ROOT_PASSWORD: beer

  web:
    image: sunrajmohawk/trsweb
    networks:
      - trs-app
    environment:
      TRS_DB_HOST: db
    ports:
      - "8080:80"
