services:
  web:
    image: sunrajmohawk/trsweb
    environment:
      TRS_DB_HOST: db
    ports:
      - ${HTTP_PORT:-80}:80

  db:
    image: sunrajmohawk/trsdb
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
    secrets:
      - db_root_password

secrets:
  db_root_password:
    file: db_root_password.txt
