services:
  web:
    image: sunrajmohawk/trsweb
    environment:
      TRS_DB_HOST: db
    ports:
      - ${HTTP_PORT:-80}:80

  db:
    image: sunrajmohawk/trsdb
    environment:
      MYSQL_ROOT_PASSWORD: beer
    volumes:
      - trs_db_data:/var/lib/docker/volumes/trs_db_data/_data

  volumes:
    trs_db_data:
      external: true
